name: Publish
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Jupyter Lab
        run: pip install jupyterlab

      - name: Install python packaging tools
        run: pip install setuptools wheel twine

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Run bump script
        run: ./scripts/dev/bump

      - name: Run build script
        run: ./scripts/dev/build

      - name: Publish package on NPM
        run: npm publish
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package on PyPI
        run: python -m twine upload dist/*
        working-directory: pypi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Bump version and publish"
          git push https://${{ secrets.GH_TOKEN }}@github.com/mme/langforge.git

      - name: Merge to main branch
        run: |
          git checkout main
          git merge --no-ff release
          git push https://${{ secrets.GH_TOKEN }}@github.com/mme/langforge.git
